//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.04 at 12:58:39 PM CEST 
//


package at.ac.tuwien.digitalpreservation.config;

import javax.xml.bind.annotation.adapters.XmlAdapter;
import at.ac.tuwien.digitalpreservation.MouseButtonEnum;

public class Adapter1
    extends XmlAdapter<String, MouseButtonEnum>
{


    public MouseButtonEnum unmarshal(String value) {
        return (at.ac.tuwien.digitalpreservation.MouseButtonEnum.parseMouseButton(value));
    }

    public String marshal(MouseButtonEnum value) {
        return (at.ac.tuwien.digitalpreservation.MouseButtonEnum.printMouseButton(value));
    }

}
