//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.06 at 07:35:21 PM CEST 
//


package at.ac.tuwien.digitalpreservation.config;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for keyboardEvent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="keyboardEvent">
 *   &lt;complexContent>
 *     &lt;extension base="{}abstractEvent">
 *       &lt;sequence>
 *         &lt;element name="scancodes" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "keyboardEvent", propOrder = {
    "scancodes"
})
public class KeyboardEvent
    extends AbstractEvent
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(type = Integer.class)
    protected List<Integer> scancodes;

    /**
     * Gets the value of the scancodes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scancodes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScancodes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Integer }
     * 
     * 
     */
    public List<Integer> getScancodes() {
        if (scancodes == null) {
            scancodes = new ArrayList<Integer>();
        }
        return this.scancodes;
    }

}
